//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppClient.WSAppTTSCP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="WSAppTTSCP", ConfigurationName="WSAppTTSCP.WSAppTTSCPSoap")]
    public interface WSAppTTSCPSoap {
        
        // CODEGEN: Generating message contract since element name email from namespace WSAppTTSCP is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WSAppTTSCP/autenticaMembro", ReplyAction="*")]
        WebAppClient.WSAppTTSCP.autenticaMembroResponse autenticaMembro(WebAppClient.WSAppTTSCP.autenticaMembroRequest request);
        
        // CODEGEN: Generating message contract since element name listaTurmasResult from namespace WSAppTTSCP is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WSAppTTSCP/listaTurmas", ReplyAction="*")]
        WebAppClient.WSAppTTSCP.listaTurmasResponse listaTurmas(WebAppClient.WSAppTTSCP.listaTurmasRequest request);
        
        // CODEGEN: Generating message contract since element name turma from namespace WSAppTTSCP is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WSAppTTSCP/criarTurma", ReplyAction="*")]
        WebAppClient.WSAppTTSCP.criarTurmaResponse criarTurma(WebAppClient.WSAppTTSCP.criarTurmaRequest request);
        
        // CODEGEN: Generating message contract since element name turma from namespace WSAppTTSCP is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WSAppTTSCP/criarMembro", ReplyAction="*")]
        WebAppClient.WSAppTTSCP.criarMembroResponse criarMembro(WebAppClient.WSAppTTSCP.criarMembroRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class autenticaMembroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="autenticaMembro", Namespace="WSAppTTSCP", Order=0)]
        public WebAppClient.WSAppTTSCP.autenticaMembroRequestBody Body;
        
        public autenticaMembroRequest() {
        }
        
        public autenticaMembroRequest(WebAppClient.WSAppTTSCP.autenticaMembroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSAppTTSCP")]
    public partial class autenticaMembroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string turma;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int tipoMembro;
        
        public autenticaMembroRequestBody() {
        }
        
        public autenticaMembroRequestBody(string email, string pass, string turma, int tipoMembro) {
            this.email = email;
            this.pass = pass;
            this.turma = turma;
            this.tipoMembro = tipoMembro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class autenticaMembroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="autenticaMembroResponse", Namespace="WSAppTTSCP", Order=0)]
        public WebAppClient.WSAppTTSCP.autenticaMembroResponseBody Body;
        
        public autenticaMembroResponse() {
        }
        
        public autenticaMembroResponse(WebAppClient.WSAppTTSCP.autenticaMembroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSAppTTSCP")]
    public partial class autenticaMembroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool autenticaMembroResult;
        
        public autenticaMembroResponseBody() {
        }
        
        public autenticaMembroResponseBody(bool autenticaMembroResult) {
            this.autenticaMembroResult = autenticaMembroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listaTurmasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listaTurmas", Namespace="WSAppTTSCP", Order=0)]
        public WebAppClient.WSAppTTSCP.listaTurmasRequestBody Body;
        
        public listaTurmasRequest() {
        }
        
        public listaTurmasRequest(WebAppClient.WSAppTTSCP.listaTurmasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class listaTurmasRequestBody {
        
        public listaTurmasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listaTurmasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listaTurmasResponse", Namespace="WSAppTTSCP", Order=0)]
        public WebAppClient.WSAppTTSCP.listaTurmasResponseBody Body;
        
        public listaTurmasResponse() {
        }
        
        public listaTurmasResponse(WebAppClient.WSAppTTSCP.listaTurmasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSAppTTSCP")]
    public partial class listaTurmasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string listaTurmasResult;
        
        public listaTurmasResponseBody() {
        }
        
        public listaTurmasResponseBody(string listaTurmasResult) {
            this.listaTurmasResult = listaTurmasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class criarTurmaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="criarTurma", Namespace="WSAppTTSCP", Order=0)]
        public WebAppClient.WSAppTTSCP.criarTurmaRequestBody Body;
        
        public criarTurmaRequest() {
        }
        
        public criarTurmaRequest(WebAppClient.WSAppTTSCP.criarTurmaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSAppTTSCP")]
    public partial class criarTurmaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string turma;
        
        public criarTurmaRequestBody() {
        }
        
        public criarTurmaRequestBody(string turma) {
            this.turma = turma;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class criarTurmaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="criarTurmaResponse", Namespace="WSAppTTSCP", Order=0)]
        public WebAppClient.WSAppTTSCP.criarTurmaResponseBody Body;
        
        public criarTurmaResponse() {
        }
        
        public criarTurmaResponse(WebAppClient.WSAppTTSCP.criarTurmaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSAppTTSCP")]
    public partial class criarTurmaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string criarTurmaResult;
        
        public criarTurmaResponseBody() {
        }
        
        public criarTurmaResponseBody(string criarTurmaResult) {
            this.criarTurmaResult = criarTurmaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class criarMembroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="criarMembro", Namespace="WSAppTTSCP", Order=0)]
        public WebAppClient.WSAppTTSCP.criarMembroRequestBody Body;
        
        public criarMembroRequest() {
        }
        
        public criarMembroRequest(WebAppClient.WSAppTTSCP.criarMembroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSAppTTSCP")]
    public partial class criarMembroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string turma;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nomeMembro;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string emailMembro;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int tipoMembro;
        
        public criarMembroRequestBody() {
        }
        
        public criarMembroRequestBody(string turma, string nomeMembro, string emailMembro, int tipoMembro) {
            this.turma = turma;
            this.nomeMembro = nomeMembro;
            this.emailMembro = emailMembro;
            this.tipoMembro = tipoMembro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class criarMembroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="criarMembroResponse", Namespace="WSAppTTSCP", Order=0)]
        public WebAppClient.WSAppTTSCP.criarMembroResponseBody Body;
        
        public criarMembroResponse() {
        }
        
        public criarMembroResponse(WebAppClient.WSAppTTSCP.criarMembroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSAppTTSCP")]
    public partial class criarMembroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string criarMembroResult;
        
        public criarMembroResponseBody() {
        }
        
        public criarMembroResponseBody(string criarMembroResult) {
            this.criarMembroResult = criarMembroResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSAppTTSCPSoapChannel : WebAppClient.WSAppTTSCP.WSAppTTSCPSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSAppTTSCPSoapClient : System.ServiceModel.ClientBase<WebAppClient.WSAppTTSCP.WSAppTTSCPSoap>, WebAppClient.WSAppTTSCP.WSAppTTSCPSoap {
        
        public WSAppTTSCPSoapClient() {
        }
        
        public WSAppTTSCPSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSAppTTSCPSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSAppTTSCPSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSAppTTSCPSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAppClient.WSAppTTSCP.autenticaMembroResponse WebAppClient.WSAppTTSCP.WSAppTTSCPSoap.autenticaMembro(WebAppClient.WSAppTTSCP.autenticaMembroRequest request) {
            return base.Channel.autenticaMembro(request);
        }
        
        public bool autenticaMembro(string email, string pass, string turma, int tipoMembro) {
            WebAppClient.WSAppTTSCP.autenticaMembroRequest inValue = new WebAppClient.WSAppTTSCP.autenticaMembroRequest();
            inValue.Body = new WebAppClient.WSAppTTSCP.autenticaMembroRequestBody();
            inValue.Body.email = email;
            inValue.Body.pass = pass;
            inValue.Body.turma = turma;
            inValue.Body.tipoMembro = tipoMembro;
            WebAppClient.WSAppTTSCP.autenticaMembroResponse retVal = ((WebAppClient.WSAppTTSCP.WSAppTTSCPSoap)(this)).autenticaMembro(inValue);
            return retVal.Body.autenticaMembroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAppClient.WSAppTTSCP.listaTurmasResponse WebAppClient.WSAppTTSCP.WSAppTTSCPSoap.listaTurmas(WebAppClient.WSAppTTSCP.listaTurmasRequest request) {
            return base.Channel.listaTurmas(request);
        }
        
        public string listaTurmas() {
            WebAppClient.WSAppTTSCP.listaTurmasRequest inValue = new WebAppClient.WSAppTTSCP.listaTurmasRequest();
            inValue.Body = new WebAppClient.WSAppTTSCP.listaTurmasRequestBody();
            WebAppClient.WSAppTTSCP.listaTurmasResponse retVal = ((WebAppClient.WSAppTTSCP.WSAppTTSCPSoap)(this)).listaTurmas(inValue);
            return retVal.Body.listaTurmasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAppClient.WSAppTTSCP.criarTurmaResponse WebAppClient.WSAppTTSCP.WSAppTTSCPSoap.criarTurma(WebAppClient.WSAppTTSCP.criarTurmaRequest request) {
            return base.Channel.criarTurma(request);
        }
        
        public string criarTurma(string turma) {
            WebAppClient.WSAppTTSCP.criarTurmaRequest inValue = new WebAppClient.WSAppTTSCP.criarTurmaRequest();
            inValue.Body = new WebAppClient.WSAppTTSCP.criarTurmaRequestBody();
            inValue.Body.turma = turma;
            WebAppClient.WSAppTTSCP.criarTurmaResponse retVal = ((WebAppClient.WSAppTTSCP.WSAppTTSCPSoap)(this)).criarTurma(inValue);
            return retVal.Body.criarTurmaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAppClient.WSAppTTSCP.criarMembroResponse WebAppClient.WSAppTTSCP.WSAppTTSCPSoap.criarMembro(WebAppClient.WSAppTTSCP.criarMembroRequest request) {
            return base.Channel.criarMembro(request);
        }
        
        public string criarMembro(string turma, string nomeMembro, string emailMembro, int tipoMembro) {
            WebAppClient.WSAppTTSCP.criarMembroRequest inValue = new WebAppClient.WSAppTTSCP.criarMembroRequest();
            inValue.Body = new WebAppClient.WSAppTTSCP.criarMembroRequestBody();
            inValue.Body.turma = turma;
            inValue.Body.nomeMembro = nomeMembro;
            inValue.Body.emailMembro = emailMembro;
            inValue.Body.tipoMembro = tipoMembro;
            WebAppClient.WSAppTTSCP.criarMembroResponse retVal = ((WebAppClient.WSAppTTSCP.WSAppTTSCPSoap)(this)).criarMembro(inValue);
            return retVal.Body.criarMembroResult;
        }
    }
}
