//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppClient.WSAppTTSCP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="WSAppTTSCP", ConfigurationName="WSAppTTSCP.WSAppTTSCPSoap")]
    public interface WSAppTTSCPSoap {
        
        // CODEGEN: Generating message contract since element name email from namespace WSAppTTSCP is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WSAppTTSCP/dadosMembro", ReplyAction="*")]
        WebAppClient.WSAppTTSCP.dadosMembroResponse dadosMembro(WebAppClient.WSAppTTSCP.dadosMembroRequest request);
        
        // CODEGEN: Generating message contract since element name turma from namespace WSAppTTSCP is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WSAppTTSCP/adicionaPesquisa", ReplyAction="*")]
        WebAppClient.WSAppTTSCP.adicionaPesquisaResponse adicionaPesquisa(WebAppClient.WSAppTTSCP.adicionaPesquisaRequest request);
        
        // CODEGEN: Generating message contract since element name turma from namespace WSAppTTSCP is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WSAppTTSCP/adicionaVotoPesquisa", ReplyAction="*")]
        WebAppClient.WSAppTTSCP.adicionaVotoPesquisaResponse adicionaVotoPesquisa(WebAppClient.WSAppTTSCP.adicionaVotoPesquisaRequest request);
        
        // CODEGEN: Generating message contract since element name turma from namespace WSAppTTSCP is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WSAppTTSCP/resultadoPesquisa", ReplyAction="*")]
        WebAppClient.WSAppTTSCP.resultadoPesquisaResponse resultadoPesquisa(WebAppClient.WSAppTTSCP.resultadoPesquisaRequest request);
        
        // CODEGEN: Generating message contract since element name turma from namespace WSAppTTSCP is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WSAppTTSCP/listaPesquisasDaTurma", ReplyAction="*")]
        WebAppClient.WSAppTTSCP.listaPesquisasDaTurmaResponse listaPesquisasDaTurma(WebAppClient.WSAppTTSCP.listaPesquisasDaTurmaRequest request);
        
        // CODEGEN: Generating message contract since element name turma from namespace WSAppTTSCP is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WSAppTTSCP/dadosTodosMembrosTurma", ReplyAction="*")]
        WebAppClient.WSAppTTSCP.dadosTodosMembrosTurmaResponse dadosTodosMembrosTurma(WebAppClient.WSAppTTSCP.dadosTodosMembrosTurmaRequest request);
        
        // CODEGEN: Generating message contract since element name dadosTodosMembrosResult from namespace WSAppTTSCP is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WSAppTTSCP/dadosTodosMembros", ReplyAction="*")]
        WebAppClient.WSAppTTSCP.dadosTodosMembrosResponse dadosTodosMembros(WebAppClient.WSAppTTSCP.dadosTodosMembrosRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace WSAppTTSCP is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WSAppTTSCP/associaMembroTurma", ReplyAction="*")]
        WebAppClient.WSAppTTSCP.associaMembroTurmaResponse associaMembroTurma(WebAppClient.WSAppTTSCP.associaMembroTurmaRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace WSAppTTSCP is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WSAppTTSCP/autenticaMembro", ReplyAction="*")]
        WebAppClient.WSAppTTSCP.autenticaMembroResponse autenticaMembro(WebAppClient.WSAppTTSCP.autenticaMembroRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace WSAppTTSCP is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WSAppTTSCP/alteraSenha", ReplyAction="*")]
        WebAppClient.WSAppTTSCP.alteraSenhaResponse alteraSenha(WebAppClient.WSAppTTSCP.alteraSenhaRequest request);
        
        // CODEGEN: Generating message contract since element name listaTurmasResult from namespace WSAppTTSCP is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WSAppTTSCP/listaTurmas", ReplyAction="*")]
        WebAppClient.WSAppTTSCP.listaTurmasResponse listaTurmas(WebAppClient.WSAppTTSCP.listaTurmasRequest request);
        
        // CODEGEN: Generating message contract since element name turma from namespace WSAppTTSCP is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WSAppTTSCP/criarTurma", ReplyAction="*")]
        WebAppClient.WSAppTTSCP.criarTurmaResponse criarTurma(WebAppClient.WSAppTTSCP.criarTurmaRequest request);
        
        // CODEGEN: Generating message contract since element name nomeMembro from namespace WSAppTTSCP is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WSAppTTSCP/criarMembro", ReplyAction="*")]
        WebAppClient.WSAppTTSCP.criarMembroResponse criarMembro(WebAppClient.WSAppTTSCP.criarMembroRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class dadosMembroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="dadosMembro", Namespace="WSAppTTSCP", Order=0)]
        public WebAppClient.WSAppTTSCP.dadosMembroRequestBody Body;
        
        public dadosMembroRequest() {
        }
        
        public dadosMembroRequest(WebAppClient.WSAppTTSCP.dadosMembroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSAppTTSCP")]
    public partial class dadosMembroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public dadosMembroRequestBody() {
        }
        
        public dadosMembroRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class dadosMembroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="dadosMembroResponse", Namespace="WSAppTTSCP", Order=0)]
        public WebAppClient.WSAppTTSCP.dadosMembroResponseBody Body;
        
        public dadosMembroResponse() {
        }
        
        public dadosMembroResponse(WebAppClient.WSAppTTSCP.dadosMembroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSAppTTSCP")]
    public partial class dadosMembroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dadosMembroResult;
        
        public dadosMembroResponseBody() {
        }
        
        public dadosMembroResponseBody(string dadosMembroResult) {
            this.dadosMembroResult = dadosMembroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class adicionaPesquisaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="adicionaPesquisa", Namespace="WSAppTTSCP", Order=0)]
        public WebAppClient.WSAppTTSCP.adicionaPesquisaRequestBody Body;
        
        public adicionaPesquisaRequest() {
        }
        
        public adicionaPesquisaRequest(WebAppClient.WSAppTTSCP.adicionaPesquisaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSAppTTSCP")]
    public partial class adicionaPesquisaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string turma;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pesquisa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string descricao;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string data;
        
        public adicionaPesquisaRequestBody() {
        }
        
        public adicionaPesquisaRequestBody(string turma, string pesquisa, string descricao, string data) {
            this.turma = turma;
            this.pesquisa = pesquisa;
            this.descricao = descricao;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class adicionaPesquisaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="adicionaPesquisaResponse", Namespace="WSAppTTSCP", Order=0)]
        public WebAppClient.WSAppTTSCP.adicionaPesquisaResponseBody Body;
        
        public adicionaPesquisaResponse() {
        }
        
        public adicionaPesquisaResponse(WebAppClient.WSAppTTSCP.adicionaPesquisaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSAppTTSCP")]
    public partial class adicionaPesquisaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string adicionaPesquisaResult;
        
        public adicionaPesquisaResponseBody() {
        }
        
        public adicionaPesquisaResponseBody(string adicionaPesquisaResult) {
            this.adicionaPesquisaResult = adicionaPesquisaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class adicionaVotoPesquisaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="adicionaVotoPesquisa", Namespace="WSAppTTSCP", Order=0)]
        public WebAppClient.WSAppTTSCP.adicionaVotoPesquisaRequestBody Body;
        
        public adicionaVotoPesquisaRequest() {
        }
        
        public adicionaVotoPesquisaRequest(WebAppClient.WSAppTTSCP.adicionaVotoPesquisaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSAppTTSCP")]
    public partial class adicionaVotoPesquisaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string turma;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idPesquisa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool voto;
        
        public adicionaVotoPesquisaRequestBody() {
        }
        
        public adicionaVotoPesquisaRequestBody(string turma, string idPesquisa, string email, bool voto) {
            this.turma = turma;
            this.idPesquisa = idPesquisa;
            this.email = email;
            this.voto = voto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class adicionaVotoPesquisaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="adicionaVotoPesquisaResponse", Namespace="WSAppTTSCP", Order=0)]
        public WebAppClient.WSAppTTSCP.adicionaVotoPesquisaResponseBody Body;
        
        public adicionaVotoPesquisaResponse() {
        }
        
        public adicionaVotoPesquisaResponse(WebAppClient.WSAppTTSCP.adicionaVotoPesquisaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSAppTTSCP")]
    public partial class adicionaVotoPesquisaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string adicionaVotoPesquisaResult;
        
        public adicionaVotoPesquisaResponseBody() {
        }
        
        public adicionaVotoPesquisaResponseBody(string adicionaVotoPesquisaResult) {
            this.adicionaVotoPesquisaResult = adicionaVotoPesquisaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class resultadoPesquisaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="resultadoPesquisa", Namespace="WSAppTTSCP", Order=0)]
        public WebAppClient.WSAppTTSCP.resultadoPesquisaRequestBody Body;
        
        public resultadoPesquisaRequest() {
        }
        
        public resultadoPesquisaRequest(WebAppClient.WSAppTTSCP.resultadoPesquisaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSAppTTSCP")]
    public partial class resultadoPesquisaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string turma;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idPesquisa;
        
        public resultadoPesquisaRequestBody() {
        }
        
        public resultadoPesquisaRequestBody(string turma, string idPesquisa) {
            this.turma = turma;
            this.idPesquisa = idPesquisa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class resultadoPesquisaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="resultadoPesquisaResponse", Namespace="WSAppTTSCP", Order=0)]
        public WebAppClient.WSAppTTSCP.resultadoPesquisaResponseBody Body;
        
        public resultadoPesquisaResponse() {
        }
        
        public resultadoPesquisaResponse(WebAppClient.WSAppTTSCP.resultadoPesquisaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSAppTTSCP")]
    public partial class resultadoPesquisaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string resultadoPesquisaResult;
        
        public resultadoPesquisaResponseBody() {
        }
        
        public resultadoPesquisaResponseBody(string resultadoPesquisaResult) {
            this.resultadoPesquisaResult = resultadoPesquisaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listaPesquisasDaTurmaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listaPesquisasDaTurma", Namespace="WSAppTTSCP", Order=0)]
        public WebAppClient.WSAppTTSCP.listaPesquisasDaTurmaRequestBody Body;
        
        public listaPesquisasDaTurmaRequest() {
        }
        
        public listaPesquisasDaTurmaRequest(WebAppClient.WSAppTTSCP.listaPesquisasDaTurmaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSAppTTSCP")]
    public partial class listaPesquisasDaTurmaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string turma;
        
        public listaPesquisasDaTurmaRequestBody() {
        }
        
        public listaPesquisasDaTurmaRequestBody(string turma) {
            this.turma = turma;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listaPesquisasDaTurmaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listaPesquisasDaTurmaResponse", Namespace="WSAppTTSCP", Order=0)]
        public WebAppClient.WSAppTTSCP.listaPesquisasDaTurmaResponseBody Body;
        
        public listaPesquisasDaTurmaResponse() {
        }
        
        public listaPesquisasDaTurmaResponse(WebAppClient.WSAppTTSCP.listaPesquisasDaTurmaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSAppTTSCP")]
    public partial class listaPesquisasDaTurmaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string listaPesquisasDaTurmaResult;
        
        public listaPesquisasDaTurmaResponseBody() {
        }
        
        public listaPesquisasDaTurmaResponseBody(string listaPesquisasDaTurmaResult) {
            this.listaPesquisasDaTurmaResult = listaPesquisasDaTurmaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class dadosTodosMembrosTurmaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="dadosTodosMembrosTurma", Namespace="WSAppTTSCP", Order=0)]
        public WebAppClient.WSAppTTSCP.dadosTodosMembrosTurmaRequestBody Body;
        
        public dadosTodosMembrosTurmaRequest() {
        }
        
        public dadosTodosMembrosTurmaRequest(WebAppClient.WSAppTTSCP.dadosTodosMembrosTurmaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSAppTTSCP")]
    public partial class dadosTodosMembrosTurmaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string turma;
        
        public dadosTodosMembrosTurmaRequestBody() {
        }
        
        public dadosTodosMembrosTurmaRequestBody(string turma) {
            this.turma = turma;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class dadosTodosMembrosTurmaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="dadosTodosMembrosTurmaResponse", Namespace="WSAppTTSCP", Order=0)]
        public WebAppClient.WSAppTTSCP.dadosTodosMembrosTurmaResponseBody Body;
        
        public dadosTodosMembrosTurmaResponse() {
        }
        
        public dadosTodosMembrosTurmaResponse(WebAppClient.WSAppTTSCP.dadosTodosMembrosTurmaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSAppTTSCP")]
    public partial class dadosTodosMembrosTurmaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dadosTodosMembrosTurmaResult;
        
        public dadosTodosMembrosTurmaResponseBody() {
        }
        
        public dadosTodosMembrosTurmaResponseBody(string dadosTodosMembrosTurmaResult) {
            this.dadosTodosMembrosTurmaResult = dadosTodosMembrosTurmaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class dadosTodosMembrosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="dadosTodosMembros", Namespace="WSAppTTSCP", Order=0)]
        public WebAppClient.WSAppTTSCP.dadosTodosMembrosRequestBody Body;
        
        public dadosTodosMembrosRequest() {
        }
        
        public dadosTodosMembrosRequest(WebAppClient.WSAppTTSCP.dadosTodosMembrosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class dadosTodosMembrosRequestBody {
        
        public dadosTodosMembrosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class dadosTodosMembrosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="dadosTodosMembrosResponse", Namespace="WSAppTTSCP", Order=0)]
        public WebAppClient.WSAppTTSCP.dadosTodosMembrosResponseBody Body;
        
        public dadosTodosMembrosResponse() {
        }
        
        public dadosTodosMembrosResponse(WebAppClient.WSAppTTSCP.dadosTodosMembrosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSAppTTSCP")]
    public partial class dadosTodosMembrosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dadosTodosMembrosResult;
        
        public dadosTodosMembrosResponseBody() {
        }
        
        public dadosTodosMembrosResponseBody(string dadosTodosMembrosResult) {
            this.dadosTodosMembrosResult = dadosTodosMembrosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class associaMembroTurmaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="associaMembroTurma", Namespace="WSAppTTSCP", Order=0)]
        public WebAppClient.WSAppTTSCP.associaMembroTurmaRequestBody Body;
        
        public associaMembroTurmaRequest() {
        }
        
        public associaMembroTurmaRequest(WebAppClient.WSAppTTSCP.associaMembroTurmaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSAppTTSCP")]
    public partial class associaMembroTurmaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string turma;
        
        public associaMembroTurmaRequestBody() {
        }
        
        public associaMembroTurmaRequestBody(string email, string turma) {
            this.email = email;
            this.turma = turma;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class associaMembroTurmaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="associaMembroTurmaResponse", Namespace="WSAppTTSCP", Order=0)]
        public WebAppClient.WSAppTTSCP.associaMembroTurmaResponseBody Body;
        
        public associaMembroTurmaResponse() {
        }
        
        public associaMembroTurmaResponse(WebAppClient.WSAppTTSCP.associaMembroTurmaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSAppTTSCP")]
    public partial class associaMembroTurmaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string associaMembroTurmaResult;
        
        public associaMembroTurmaResponseBody() {
        }
        
        public associaMembroTurmaResponseBody(string associaMembroTurmaResult) {
            this.associaMembroTurmaResult = associaMembroTurmaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class autenticaMembroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="autenticaMembro", Namespace="WSAppTTSCP", Order=0)]
        public WebAppClient.WSAppTTSCP.autenticaMembroRequestBody Body;
        
        public autenticaMembroRequest() {
        }
        
        public autenticaMembroRequest(WebAppClient.WSAppTTSCP.autenticaMembroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSAppTTSCP")]
    public partial class autenticaMembroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public autenticaMembroRequestBody() {
        }
        
        public autenticaMembroRequestBody(string email, string pass) {
            this.email = email;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class autenticaMembroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="autenticaMembroResponse", Namespace="WSAppTTSCP", Order=0)]
        public WebAppClient.WSAppTTSCP.autenticaMembroResponseBody Body;
        
        public autenticaMembroResponse() {
        }
        
        public autenticaMembroResponse(WebAppClient.WSAppTTSCP.autenticaMembroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSAppTTSCP")]
    public partial class autenticaMembroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool autenticaMembroResult;
        
        public autenticaMembroResponseBody() {
        }
        
        public autenticaMembroResponseBody(bool autenticaMembroResult) {
            this.autenticaMembroResult = autenticaMembroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class alteraSenhaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="alteraSenha", Namespace="WSAppTTSCP", Order=0)]
        public WebAppClient.WSAppTTSCP.alteraSenhaRequestBody Body;
        
        public alteraSenhaRequest() {
        }
        
        public alteraSenhaRequest(WebAppClient.WSAppTTSCP.alteraSenhaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSAppTTSCP")]
    public partial class alteraSenhaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string currentPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string newPass;
        
        public alteraSenhaRequestBody() {
        }
        
        public alteraSenhaRequestBody(string email, string currentPass, string newPass) {
            this.email = email;
            this.currentPass = currentPass;
            this.newPass = newPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class alteraSenhaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="alteraSenhaResponse", Namespace="WSAppTTSCP", Order=0)]
        public WebAppClient.WSAppTTSCP.alteraSenhaResponseBody Body;
        
        public alteraSenhaResponse() {
        }
        
        public alteraSenhaResponse(WebAppClient.WSAppTTSCP.alteraSenhaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSAppTTSCP")]
    public partial class alteraSenhaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string alteraSenhaResult;
        
        public alteraSenhaResponseBody() {
        }
        
        public alteraSenhaResponseBody(string alteraSenhaResult) {
            this.alteraSenhaResult = alteraSenhaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listaTurmasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listaTurmas", Namespace="WSAppTTSCP", Order=0)]
        public WebAppClient.WSAppTTSCP.listaTurmasRequestBody Body;
        
        public listaTurmasRequest() {
        }
        
        public listaTurmasRequest(WebAppClient.WSAppTTSCP.listaTurmasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class listaTurmasRequestBody {
        
        public listaTurmasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listaTurmasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listaTurmasResponse", Namespace="WSAppTTSCP", Order=0)]
        public WebAppClient.WSAppTTSCP.listaTurmasResponseBody Body;
        
        public listaTurmasResponse() {
        }
        
        public listaTurmasResponse(WebAppClient.WSAppTTSCP.listaTurmasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSAppTTSCP")]
    public partial class listaTurmasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string listaTurmasResult;
        
        public listaTurmasResponseBody() {
        }
        
        public listaTurmasResponseBody(string listaTurmasResult) {
            this.listaTurmasResult = listaTurmasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class criarTurmaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="criarTurma", Namespace="WSAppTTSCP", Order=0)]
        public WebAppClient.WSAppTTSCP.criarTurmaRequestBody Body;
        
        public criarTurmaRequest() {
        }
        
        public criarTurmaRequest(WebAppClient.WSAppTTSCP.criarTurmaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSAppTTSCP")]
    public partial class criarTurmaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string turma;
        
        public criarTurmaRequestBody() {
        }
        
        public criarTurmaRequestBody(string turma) {
            this.turma = turma;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class criarTurmaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="criarTurmaResponse", Namespace="WSAppTTSCP", Order=0)]
        public WebAppClient.WSAppTTSCP.criarTurmaResponseBody Body;
        
        public criarTurmaResponse() {
        }
        
        public criarTurmaResponse(WebAppClient.WSAppTTSCP.criarTurmaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSAppTTSCP")]
    public partial class criarTurmaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string criarTurmaResult;
        
        public criarTurmaResponseBody() {
        }
        
        public criarTurmaResponseBody(string criarTurmaResult) {
            this.criarTurmaResult = criarTurmaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class criarMembroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="criarMembro", Namespace="WSAppTTSCP", Order=0)]
        public WebAppClient.WSAppTTSCP.criarMembroRequestBody Body;
        
        public criarMembroRequest() {
        }
        
        public criarMembroRequest(WebAppClient.WSAppTTSCP.criarMembroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSAppTTSCP")]
    public partial class criarMembroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nomeMembro;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string emailMembro;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int tipoMembro;
        
        public criarMembroRequestBody() {
        }
        
        public criarMembroRequestBody(string nomeMembro, string emailMembro, int tipoMembro) {
            this.nomeMembro = nomeMembro;
            this.emailMembro = emailMembro;
            this.tipoMembro = tipoMembro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class criarMembroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="criarMembroResponse", Namespace="WSAppTTSCP", Order=0)]
        public WebAppClient.WSAppTTSCP.criarMembroResponseBody Body;
        
        public criarMembroResponse() {
        }
        
        public criarMembroResponse(WebAppClient.WSAppTTSCP.criarMembroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSAppTTSCP")]
    public partial class criarMembroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string criarMembroResult;
        
        public criarMembroResponseBody() {
        }
        
        public criarMembroResponseBody(string criarMembroResult) {
            this.criarMembroResult = criarMembroResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSAppTTSCPSoapChannel : WebAppClient.WSAppTTSCP.WSAppTTSCPSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSAppTTSCPSoapClient : System.ServiceModel.ClientBase<WebAppClient.WSAppTTSCP.WSAppTTSCPSoap>, WebAppClient.WSAppTTSCP.WSAppTTSCPSoap {
        
        public WSAppTTSCPSoapClient() {
        }
        
        public WSAppTTSCPSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSAppTTSCPSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSAppTTSCPSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSAppTTSCPSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAppClient.WSAppTTSCP.dadosMembroResponse WebAppClient.WSAppTTSCP.WSAppTTSCPSoap.dadosMembro(WebAppClient.WSAppTTSCP.dadosMembroRequest request) {
            return base.Channel.dadosMembro(request);
        }
        
        public string dadosMembro(string email) {
            WebAppClient.WSAppTTSCP.dadosMembroRequest inValue = new WebAppClient.WSAppTTSCP.dadosMembroRequest();
            inValue.Body = new WebAppClient.WSAppTTSCP.dadosMembroRequestBody();
            inValue.Body.email = email;
            WebAppClient.WSAppTTSCP.dadosMembroResponse retVal = ((WebAppClient.WSAppTTSCP.WSAppTTSCPSoap)(this)).dadosMembro(inValue);
            return retVal.Body.dadosMembroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAppClient.WSAppTTSCP.adicionaPesquisaResponse WebAppClient.WSAppTTSCP.WSAppTTSCPSoap.adicionaPesquisa(WebAppClient.WSAppTTSCP.adicionaPesquisaRequest request) {
            return base.Channel.adicionaPesquisa(request);
        }
        
        public string adicionaPesquisa(string turma, string pesquisa, string descricao, string data) {
            WebAppClient.WSAppTTSCP.adicionaPesquisaRequest inValue = new WebAppClient.WSAppTTSCP.adicionaPesquisaRequest();
            inValue.Body = new WebAppClient.WSAppTTSCP.adicionaPesquisaRequestBody();
            inValue.Body.turma = turma;
            inValue.Body.pesquisa = pesquisa;
            inValue.Body.descricao = descricao;
            inValue.Body.data = data;
            WebAppClient.WSAppTTSCP.adicionaPesquisaResponse retVal = ((WebAppClient.WSAppTTSCP.WSAppTTSCPSoap)(this)).adicionaPesquisa(inValue);
            return retVal.Body.adicionaPesquisaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAppClient.WSAppTTSCP.adicionaVotoPesquisaResponse WebAppClient.WSAppTTSCP.WSAppTTSCPSoap.adicionaVotoPesquisa(WebAppClient.WSAppTTSCP.adicionaVotoPesquisaRequest request) {
            return base.Channel.adicionaVotoPesquisa(request);
        }
        
        public string adicionaVotoPesquisa(string turma, string idPesquisa, string email, bool voto) {
            WebAppClient.WSAppTTSCP.adicionaVotoPesquisaRequest inValue = new WebAppClient.WSAppTTSCP.adicionaVotoPesquisaRequest();
            inValue.Body = new WebAppClient.WSAppTTSCP.adicionaVotoPesquisaRequestBody();
            inValue.Body.turma = turma;
            inValue.Body.idPesquisa = idPesquisa;
            inValue.Body.email = email;
            inValue.Body.voto = voto;
            WebAppClient.WSAppTTSCP.adicionaVotoPesquisaResponse retVal = ((WebAppClient.WSAppTTSCP.WSAppTTSCPSoap)(this)).adicionaVotoPesquisa(inValue);
            return retVal.Body.adicionaVotoPesquisaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAppClient.WSAppTTSCP.resultadoPesquisaResponse WebAppClient.WSAppTTSCP.WSAppTTSCPSoap.resultadoPesquisa(WebAppClient.WSAppTTSCP.resultadoPesquisaRequest request) {
            return base.Channel.resultadoPesquisa(request);
        }
        
        public string resultadoPesquisa(string turma, string idPesquisa) {
            WebAppClient.WSAppTTSCP.resultadoPesquisaRequest inValue = new WebAppClient.WSAppTTSCP.resultadoPesquisaRequest();
            inValue.Body = new WebAppClient.WSAppTTSCP.resultadoPesquisaRequestBody();
            inValue.Body.turma = turma;
            inValue.Body.idPesquisa = idPesquisa;
            WebAppClient.WSAppTTSCP.resultadoPesquisaResponse retVal = ((WebAppClient.WSAppTTSCP.WSAppTTSCPSoap)(this)).resultadoPesquisa(inValue);
            return retVal.Body.resultadoPesquisaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAppClient.WSAppTTSCP.listaPesquisasDaTurmaResponse WebAppClient.WSAppTTSCP.WSAppTTSCPSoap.listaPesquisasDaTurma(WebAppClient.WSAppTTSCP.listaPesquisasDaTurmaRequest request) {
            return base.Channel.listaPesquisasDaTurma(request);
        }
        
        public string listaPesquisasDaTurma(string turma) {
            WebAppClient.WSAppTTSCP.listaPesquisasDaTurmaRequest inValue = new WebAppClient.WSAppTTSCP.listaPesquisasDaTurmaRequest();
            inValue.Body = new WebAppClient.WSAppTTSCP.listaPesquisasDaTurmaRequestBody();
            inValue.Body.turma = turma;
            WebAppClient.WSAppTTSCP.listaPesquisasDaTurmaResponse retVal = ((WebAppClient.WSAppTTSCP.WSAppTTSCPSoap)(this)).listaPesquisasDaTurma(inValue);
            return retVal.Body.listaPesquisasDaTurmaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAppClient.WSAppTTSCP.dadosTodosMembrosTurmaResponse WebAppClient.WSAppTTSCP.WSAppTTSCPSoap.dadosTodosMembrosTurma(WebAppClient.WSAppTTSCP.dadosTodosMembrosTurmaRequest request) {
            return base.Channel.dadosTodosMembrosTurma(request);
        }
        
        public string dadosTodosMembrosTurma(string turma) {
            WebAppClient.WSAppTTSCP.dadosTodosMembrosTurmaRequest inValue = new WebAppClient.WSAppTTSCP.dadosTodosMembrosTurmaRequest();
            inValue.Body = new WebAppClient.WSAppTTSCP.dadosTodosMembrosTurmaRequestBody();
            inValue.Body.turma = turma;
            WebAppClient.WSAppTTSCP.dadosTodosMembrosTurmaResponse retVal = ((WebAppClient.WSAppTTSCP.WSAppTTSCPSoap)(this)).dadosTodosMembrosTurma(inValue);
            return retVal.Body.dadosTodosMembrosTurmaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAppClient.WSAppTTSCP.dadosTodosMembrosResponse WebAppClient.WSAppTTSCP.WSAppTTSCPSoap.dadosTodosMembros(WebAppClient.WSAppTTSCP.dadosTodosMembrosRequest request) {
            return base.Channel.dadosTodosMembros(request);
        }
        
        public string dadosTodosMembros() {
            WebAppClient.WSAppTTSCP.dadosTodosMembrosRequest inValue = new WebAppClient.WSAppTTSCP.dadosTodosMembrosRequest();
            inValue.Body = new WebAppClient.WSAppTTSCP.dadosTodosMembrosRequestBody();
            WebAppClient.WSAppTTSCP.dadosTodosMembrosResponse retVal = ((WebAppClient.WSAppTTSCP.WSAppTTSCPSoap)(this)).dadosTodosMembros(inValue);
            return retVal.Body.dadosTodosMembrosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAppClient.WSAppTTSCP.associaMembroTurmaResponse WebAppClient.WSAppTTSCP.WSAppTTSCPSoap.associaMembroTurma(WebAppClient.WSAppTTSCP.associaMembroTurmaRequest request) {
            return base.Channel.associaMembroTurma(request);
        }
        
        public string associaMembroTurma(string email, string turma) {
            WebAppClient.WSAppTTSCP.associaMembroTurmaRequest inValue = new WebAppClient.WSAppTTSCP.associaMembroTurmaRequest();
            inValue.Body = new WebAppClient.WSAppTTSCP.associaMembroTurmaRequestBody();
            inValue.Body.email = email;
            inValue.Body.turma = turma;
            WebAppClient.WSAppTTSCP.associaMembroTurmaResponse retVal = ((WebAppClient.WSAppTTSCP.WSAppTTSCPSoap)(this)).associaMembroTurma(inValue);
            return retVal.Body.associaMembroTurmaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAppClient.WSAppTTSCP.autenticaMembroResponse WebAppClient.WSAppTTSCP.WSAppTTSCPSoap.autenticaMembro(WebAppClient.WSAppTTSCP.autenticaMembroRequest request) {
            return base.Channel.autenticaMembro(request);
        }
        
        public bool autenticaMembro(string email, string pass) {
            WebAppClient.WSAppTTSCP.autenticaMembroRequest inValue = new WebAppClient.WSAppTTSCP.autenticaMembroRequest();
            inValue.Body = new WebAppClient.WSAppTTSCP.autenticaMembroRequestBody();
            inValue.Body.email = email;
            inValue.Body.pass = pass;
            WebAppClient.WSAppTTSCP.autenticaMembroResponse retVal = ((WebAppClient.WSAppTTSCP.WSAppTTSCPSoap)(this)).autenticaMembro(inValue);
            return retVal.Body.autenticaMembroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAppClient.WSAppTTSCP.alteraSenhaResponse WebAppClient.WSAppTTSCP.WSAppTTSCPSoap.alteraSenha(WebAppClient.WSAppTTSCP.alteraSenhaRequest request) {
            return base.Channel.alteraSenha(request);
        }
        
        public string alteraSenha(string email, string currentPass, string newPass) {
            WebAppClient.WSAppTTSCP.alteraSenhaRequest inValue = new WebAppClient.WSAppTTSCP.alteraSenhaRequest();
            inValue.Body = new WebAppClient.WSAppTTSCP.alteraSenhaRequestBody();
            inValue.Body.email = email;
            inValue.Body.currentPass = currentPass;
            inValue.Body.newPass = newPass;
            WebAppClient.WSAppTTSCP.alteraSenhaResponse retVal = ((WebAppClient.WSAppTTSCP.WSAppTTSCPSoap)(this)).alteraSenha(inValue);
            return retVal.Body.alteraSenhaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAppClient.WSAppTTSCP.listaTurmasResponse WebAppClient.WSAppTTSCP.WSAppTTSCPSoap.listaTurmas(WebAppClient.WSAppTTSCP.listaTurmasRequest request) {
            return base.Channel.listaTurmas(request);
        }
        
        public string listaTurmas() {
            WebAppClient.WSAppTTSCP.listaTurmasRequest inValue = new WebAppClient.WSAppTTSCP.listaTurmasRequest();
            inValue.Body = new WebAppClient.WSAppTTSCP.listaTurmasRequestBody();
            WebAppClient.WSAppTTSCP.listaTurmasResponse retVal = ((WebAppClient.WSAppTTSCP.WSAppTTSCPSoap)(this)).listaTurmas(inValue);
            return retVal.Body.listaTurmasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAppClient.WSAppTTSCP.criarTurmaResponse WebAppClient.WSAppTTSCP.WSAppTTSCPSoap.criarTurma(WebAppClient.WSAppTTSCP.criarTurmaRequest request) {
            return base.Channel.criarTurma(request);
        }
        
        public string criarTurma(string turma) {
            WebAppClient.WSAppTTSCP.criarTurmaRequest inValue = new WebAppClient.WSAppTTSCP.criarTurmaRequest();
            inValue.Body = new WebAppClient.WSAppTTSCP.criarTurmaRequestBody();
            inValue.Body.turma = turma;
            WebAppClient.WSAppTTSCP.criarTurmaResponse retVal = ((WebAppClient.WSAppTTSCP.WSAppTTSCPSoap)(this)).criarTurma(inValue);
            return retVal.Body.criarTurmaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAppClient.WSAppTTSCP.criarMembroResponse WebAppClient.WSAppTTSCP.WSAppTTSCPSoap.criarMembro(WebAppClient.WSAppTTSCP.criarMembroRequest request) {
            return base.Channel.criarMembro(request);
        }
        
        public string criarMembro(string nomeMembro, string emailMembro, int tipoMembro) {
            WebAppClient.WSAppTTSCP.criarMembroRequest inValue = new WebAppClient.WSAppTTSCP.criarMembroRequest();
            inValue.Body = new WebAppClient.WSAppTTSCP.criarMembroRequestBody();
            inValue.Body.nomeMembro = nomeMembro;
            inValue.Body.emailMembro = emailMembro;
            inValue.Body.tipoMembro = tipoMembro;
            WebAppClient.WSAppTTSCP.criarMembroResponse retVal = ((WebAppClient.WSAppTTSCP.WSAppTTSCPSoap)(this)).criarMembro(inValue);
            return retVal.Body.criarMembroResult;
        }
    }
}
